[package]
name = "my-azure-storage-sdk"
version = "0.1.1"
authors = ["Andrey <amigin@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-xml-reader = { branch = "main", git = "https://github.com/MyJetTools/my-xml-reader" }
flurl = { branch = "0.1.1", git = "https://github.com/MyJetTools/fl-url" }
my-telemetry = { branch = "main", git = "https://github.com/MyJetTools/my-telemetry.git" }
rust-extensions = { branch = "main", git = "https://github.com/MyJetTools/rust-extensions.git" }
hmac = "*"
sha2 = "*"
base64 = "*"
chrono = "*"
hyper = { version = "*", features = ["full"] }
tokio = { version = "*", features = ["macros"] }
async-trait = "*"
