[package]
name = "my-azure-storage"
version = "0.1.0"
authors = ["Andrey <amigin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-xml-reader = { git = "https://github.com/MyJetTools/my-xml-reader" }
flurl = { git = "https://github.com/MyJetTools/fl-url" }
hmac = "*"
sha2 = "*"
base64 = "*"
chrono = "0.4.19"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "*", features = ["macros"] }
